version: "3.6"

services:
  influxdb:
    # Version 2 does not have auto-configuration using ENVs
    image: influxdb:1.8
    volumes:
      - influxdb-storage:/var/lib/influxdb
      # Ensure it uses the same timezone than the server
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # Enforce authentication
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      # Admin/RW permissions (for populating DB)
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      # Readonly permissions (fer reading DB values)
      - INFLUXDB_READ_USER=${INFLUXDB_READ_USERNAME}
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_PASSWORD}
    networks:
      - influx

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    depends_on:
      - influxdb
    networks:
      - influx
    volumes:
      # Provision Telegraf with its parametrized configuration
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      # This file contains the last output from executing the example script
      - ./metrics.out:/tmp/metrics.out:ro
      # Ensure it uses the same timezone than the server
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # These variables are used in telegraf.conf
      - INFLUXDB_DATABASE=${INFLUXDB_DATABASE}
      # Telegraf needs admin permissions to create the initial DB if needed
      - INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      # Provision Grafana with initial configurations:
      # - Datasource: InfluxDB
      # - Dashborad: Use data extracted from example sceript execution
      - ./provisioning:/etc/grafana/provisioning
      # Ensure it uses the same timezone than the server
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - influxdb
    networks:
      # Allow access to retrieve data from influx (readonly)
      - influx
      # Allow access from/to Internet
      - grafana
    environment:
      # Set Grafana credentials
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      # Set DB credentials (using parametrized values in provisioning/datasources)
      - INFLUXDB_DATABASE=${INFLUXDB_DATABASE}
      - INFLUXDB_USERNAME=${INFLUXDB_READ_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_READ_PASSWORD}
      # Set Home/initial dashboard
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json

# InfluxDB network is not exposed
networks:
   influx:
     internal: true
   grafana:

volumes:
  influxdb-storage:
  grafana-storage:
